{{-- <x-front-layout title="Two Factor Authentication">
    <x-slot name="css">
        <!-- icheck bootstrap -->
        <link rel="stylesheet" href="{{ asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    </x-slot>
    <x-slot name="content">
        <div class="login-box">
            <div class="login-logo">
                <a href="{{ route('home') }}"><b>{{ config('app.name') }}</b></a>
            </div>
            <!-- /.login-logo -->
            <div class="card">
                <div class="card-body">
                    <div class="title">
                        <h1 class="text-center">Two Factor Authentication</h1>
                        <p>Enter the verification code generated by your mobile application.</p>
                    </div>
                    <form action="{{ route('two-factor.login') }}" method="post">
                        @csrf
                        <div class="input-group mb-3">
                            <input type="text" class="form-control @error('code') is-invalid @enderror"
                                name="code" placeholder="Verification Code" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                            @error('code')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <button type="submit" class="btn btn-primary btn-block">Verify</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>
                </div>
                <!-- /.login-card-body -->
            </div>
        </div>
    </x-slot>
</x-front-layout> --}}
<x-front-layout title="Two Factor Authentication">

    <!-- Start Account Login Area -->
    <div class="account-login section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
                    <form class="card login-form" action="{{ route('two-factor.enable') }}" method="post">
                        @csrf
                        <div class="card-body">
                            <div class="title">
                                <h3>Two Factor Authentication</h3>
                                <p>You can enable two factor authentication for your account.</p>
                            </div>
                            @if (session('status') == 'two-factor-authentication-enabled')
                                <div class="alert alert-success" role="alert">
                                    Two factor authentication has been enabled.
                                </div>
                            @endif
                            <div class="button">
                                @if (Auth()->user()->two_factor_secret)
                                    <div class="form-group">
                                        {!! $user->twoFactorQrCodeSvg() !!}
                                    </div>
                                    <h3>Recovery Codes</h3>
                                    <ul>
                                        @foreach (json_decode(decrypt($user->two_factor_recovery_codes)) as $code)
                                            <li>{{ $code }}</li>
                                        @endforeach
                                    </ul>
                                    <div class="form-group">
                                        <label for="recovery_code">Recovery Code</label>
                                        <input type="text" name="recovery_code" id="recovery_code"
                                            class="form-control" required>
                                    </div>
                                    @method('delete')
                                    <button class="btn" type="submit">Disable</button>
                                @else
                                    <button class="btn" type="submit">Enable</button>
                                @endif
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- End Account Login Area -->

</x-front-layout>
